"""
遊戲常數定義
"""

# 視窗設定
WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 768
FPS = 60

# 顏色定義 (RGB)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
GRAY = (128, 128, 128)
BROWN = (139, 69, 19)

# 玩家設定
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 60
PLAYER_SPEED = 5
PLAYER_JUMP_SPEED = 15
PLAYER_DOUBLE_JUMP_SPEED = 12  # 二段跳速度
GRAVITY = 0.8
GROUND_Y = WINDOW_HEIGHT - 100

# 拳頭設定
FIST_SIZE = 20
FIST_CHARGED_SIZE = 35
FIST_MAX_DISTANCE = 80
FIST_CHARGED_MAX_DISTANCE = 150  # 蓄力攻擊距離更遠
FIST_SPEED = 10
FIST_CHARGED_SPEED = 18  # 蓄力攻擊速度更快
FIST_RETURN_SPEED = 15

# 蓄力攻擊設定
CHARGE_TIME = 1000  # 蓄力時間 1 秒（毫秒）
CHARGE_DAMAGE_MULTIPLIER = 2  # 蓄力攻擊傷害倍數
STUN_DURATION = 100  # 眩暈持續時間（毫秒）

# 防禦設定
DEFENSE_DURATION = 1000  # 毫秒
DEFENSE_COOLDOWN = 3000  # 毫秒

# 無敵時間
INVINCIBLE_DURATION = 500  # 毫秒

# 滑行設定
SLIDE_DISTANCE = 100
SLIDE_SPEED = 8
SLIDE_ATTACK_DAMAGE = 0.5  # 滑行攻擊傷害
SLIDE_ATTACK_KNOCKBACK = 80  # 滑行攻擊擊退力度

# 敵人設定
DUMMY_WIDTH = 40
DUMMY_HEIGHT = 70
DUMMY_HEALTH = 10  # 增加訓練人偶血量：從3提升到10

SMALL_ROBOT_WIDTH = 45
SMALL_ROBOT_HEIGHT = 50
SMALL_ROBOT_SPEED = 3
SMALL_ROBOT_CHARGE_SPEED = 8
SMALL_ROBOT_HEALTH = 5  # 增加血量：需要5次普通攻擊或2次蓄力攻擊
SMALL_ROBOT_JUMP_SPEED = 16  # 敵人跳躍速度（調高從12到16）
SMALL_ROBOT_DOUBLE_JUMP_SPEED = 14  # 敵人二段跳速度（調高從10到14）

BOSS_WIDTH = 80
BOSS_HEIGHT = 100
BOSS_SPEED = 2
BOSS_HEALTH = 25  # 增加BOSS血量：從10提升到25
BOSS_SPECIAL_ATTACK_THRESHOLD = 0.5  # 血量低於50%時觸發特殊攻擊
BOSS_JUMP_SPEED = 16  # BOSS跳躍速度（提高從14到16，增強跳躍能力）
BOSS_DOUBLE_JUMP_SPEED = 14  # BOSS二段跳速度（提高從12到14）

# BOSS遠程攻擊設定
BOSS_BULLET_SPEED = 8
BOSS_BULLET_SIZE = 8
BOSS_RANGED_ATTACK_DISTANCE = 200  # 玩家距離超過此距離時使用遠程攻擊
BOSS_RANGED_ATTACK_COOLDOWN = 2000  # 遠程攻擊冷卻時間（毫秒）

# 新增：精英機甲兵設定
ELITE_MECH_WIDTH = 60
ELITE_MECH_HEIGHT = 70
ELITE_MECH_HEALTH = 8  # 增加精英機甲兵血量：從5提升到8
ELITE_MECH_SPEED = 2.5
ELITE_MECH_JUMP_SPEED = 18
ELITE_MECH_DOUBLE_JUMP_SPEED = 15

# 新增：反擊系統設定
COUNTER_ATTACK_WINDOW = 300  # 反擊窗口時間（毫秒）
PERFECT_DEFENSE_WINDOW = 100  # 完美防禦窗口時間（毫秒）
COUNTER_ATTACK_DAMAGE = 2  # 反擊基礎傷害
PERFECT_COUNTER_DAMAGE = 3  # 完美反擊傷害

# 新增：連擊系統設定
COMBO_WINDOW = 2000  # 連擊窗口時間（毫秒）
MAX_COMBO = 10  # 最大連擊數
COMBO_DAMAGE_TIER_1 = 3  # 3連擊以上的傷害倍數
COMBO_DAMAGE_TIER_2 = 5  # 5連擊以上的傷害倍數
COMBO_MULTIPLIER_TIER_1 = 1.25  # 3連擊以上傷害倍數
COMBO_MULTIPLIER_TIER_2 = 1.5  # 5連擊以上傷害倍數

# 攻擊設定
AIR_ATTACK_DAMAGE_MULTIPLIER = 1.5  # 空中攻擊傷害倍數

# 蓄力攻擊衝刺設定
CHARGED_ATTACK_DASH_DISTANCE = 40  # 蓄力攻擊後的衝刺距離
CHARGED_ATTACK_DASH_SPEED = 8  # 蓄力攻擊衝刺速度

# 清屏技能設定
CLEAR_SCREEN_COOLDOWN = 10000  # 清屏技能冷卻時間（10秒）
CLEAR_SCREEN_KNOCKBACK = 120  # 清屏技能擊退力度
CLEAR_SCREEN_RANGE = 300  # 清屏技能作用範圍（修正：從30000改為300）

# 特效系統設定
PARTICLE_MAX_COUNT = 200  # 最大粒子數量
EFFECT_RING_DEFAULT_LIFETIME = 60  # 光環特效預設生命值
TEXT_EFFECT_DEFAULT_LIFETIME = 90  # 文字特效預設生命值
EXPLOSION_PARTICLE_COUNT = 15  # 爆炸粒子數量
COMBO_EFFECT_THRESHOLD = 3  # 連擊特效觸發閾值
CRITICAL_HIT_CHANCE = 0.1  # 暴擊機率
PARTICLE_GRAVITY = 0.1  # 粒子重力
HEALING_PARTICLE_COUNT = 8  # 治療粒子數量

# 特效顏色設定
EFFECT_COLOR_NORMAL = YELLOW  # 普通特效顏色
EFFECT_COLOR_CRITICAL = RED  # 暴擊特效顏色
EFFECT_COLOR_COMBO = (255, 165, 0)  # 連擊特效顏色（橙色）
EFFECT_COLOR_HEALING = GREEN  # 治療特效顏色
EFFECT_COLOR_DEFENSE = BLUE  # 防禦特效顏色
EFFECT_COLOR_MAGIC = (150, 0, 255)  # 魔法特效顏色（紫色）

# 血量道具設定
HEALTH_ITEM_SPAWN_INTERVAL = 30000  # 血量道具生成間隔（30秒）
HEALTH_ITEM_SIZE = 25  # 血量道具大小
HEALTH_ITEM_RESTORE = 1  # 血量道具恢復的生命值

# 法師機器人設定
MAGE_ROBOT_WIDTH = 40
MAGE_ROBOT_HEIGHT = 55
MAGE_ROBOT_HEALTH = 4
MAGE_ROBOT_SPEED = 1.5  # 移動速度較慢
MAGE_ROBOT_ATTACK_RANGE = 400  # 攻擊範圍
MAGE_ROBOT_BULLET_SPEED = 1  # 追蹤子彈速度
MAGE_ROBOT_BULLET_SIZE = 40  # 追蹤子彈大小
MAGE_ROBOT_ATTACK_COOLDOWN = 3000  # 攻擊冷卻時間

# 法師跳躍系統設定
MAGE_ROBOT_JUMP_SPEED = 14  # 法師跳躍速度
MAGE_ROBOT_DOUBLE_JUMP_SPEED = 12  # 法師二段跳速度
MAGE_ROBOT_JUMP_COOLDOWN = 4000  # 法師跳躍冷卻時間（4秒）
MAGE_ROBOT_TELEPORT_COOLDOWN = 8000  # 法師瞬移冷卻時間（8秒）
MAGE_ROBOT_TELEPORT_RANGE = 200  # 法師瞬移範圍

# 追蹤子彈設定
TRACKING_BULLET_SPEED = 6
TRACKING_BULLET_SIZE = 12
TRACKING_BULLET_TRACKING_STRENGTH = 0.07  # 追蹤強度
TRACKING_BULLET_LIFETIME = 3000  # 子彈存在時間（3秒）

# 平台設定
PLATFORM_COLOR = (100, 100, 100)  # 平台顏色（灰色）
PLATFORM_BORDER_COLOR = (200, 200, 200)  # 平台邊框顏色

# 擊退設定
KNOCKBACK_FORCE = 50  # 擊退力度
KNOCKBACK_DURATION = 200  # 擊退持續時間（毫秒）

# 遊戲狀態
MENU_STATE = "menu"
GAME_STATE = "game"
LEVEL_SELECT_STATE = "level_select"
GAME_OVER_STATE = "game_over"
INSTRUCTIONS_STATE = "instructions"

# 關卡設定
LEVEL_1 = 1  # 訓練場
LEVEL_2 = 2  # 工廠
LEVEL_2_5 = 2.5  # 廢棄工廠（隱藏關卡）
LEVEL_3 = 3  # 實驗室（BOSS）

# 字體設定
FONT_LARGE_SIZE = 48
FONT_MEDIUM_SIZE = 32
FONT_SMALL_SIZE = 24
FONT_TINY_SIZE = 18
CHINESE_FONTS = [
    "C:/Windows/Fonts/msjh.ttc",  # 微軟正黑體
    "C:/Windows/Fonts/msyh.ttc",  # 微軟雅黑
    "C:/Windows/Fonts/mingliu.ttc",  # 細明體
    "C:/Windows/Fonts/simsun.ttc",  # 宋體
]

# 音效設定
SOUND_ENABLED = True  # 音效啟用狀態
SOUND_VOLUME = 0.7  # 預設音量 (0.0 - 1.0)
SOUND_HIT_NORMAL = "normal_hit"  # 普通攻擊擊中音效
SOUND_HIT_CHARGED = "charged_hit"  # 蓄力攻擊擊中音效
SOUND_CLEAR_SCREEN = "clear_screen"  # 清屏技能音效
